spring:
  application:
    name: eureka
server:
  port: 8761

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    lease-expiration-duration-in-seconds: 2

#zuul:
#  routes:
#    account-service:
#      path: /**
#      stripPrefix: false
#      serviceId: ACCOUNT-SERVICE
